### PR TITLE
Fix eh landing pads being preemptible

### LINKED ISSUE #512: Fix symbol preemption for call site landing pads
Currently landing pads use:
```
.chericap foo + .Ltmp - .Lfunc_begin
```
(where `foo` is the function name, `.Ltmp` is a label at the landing pad and `.Lfunc_begin` is a non-preemptible label at the same location as `foo`)
This means we use the preemptible symbol which is (a) more expensive as it has to be preserved through to run time (b) wrong in the case it actually gets preempted (in practice the landing pad is unlikely to be needed as the function itself won't be called, but -Bsymbolic and -fno-semantic-interposition can result in such situations arising).

Fixing this will require:
1. Emitting type + size information for the `.Lfunc_begin` symbols
2. Using them in place of the preemptible function symbol

NB: We should also check we emit type + size information for the `.Lfoo$local` symbols used with -fno-semantic-interposition

### PR DESCRIPTION
**Pull request by arichardson**
Fixes #512

### CODE REVIEW

File: lld/ELF/Arch/Cheri.cpp [hunk 1]
```diff
@@ -1101,44 +1101,15 @@ void addCapabilityRelocation(Symbol *sym, RelType type, InputSectionBase *sec,
...
-      assert(sym->isFunc() && "This should only be used for functions");
-      assert(sym->binding == llvm::ELF::STB_GLOBAL);
-      assert(!sym->isPreemptible);
-    }
+    // We previously had an ugly workaround here to create a hidden alias for
+    // relocations in the exception table, but this has since been fixed in
+    // the compiler. Add an explicit error here in case someone tries to
+    // link against object files/static libraries from an old toolchain.
+    errorOrWarn("got relocation against preemptible symbol " + toString(*sym) +
+                " in exception handling table. Please update your compiler!\n"
```
Comment (jrtc27) [inline lld/ELF/Arch/Cheri.cpp:1110]: If they're seeing this they _have_ updated their toolchain, but they need to do a clean rebuild of whatever they're trying to link

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp [hunk 2]
```diff
@@ -1437,6 +1438,20 @@ void AsmPrinter::emitFunctionBody() {
...
+      // See https://github.com/CTSRD-CHERI/llvm-project/issues/512.
+      // Note: We add .local so that the symbol is not deleted after assembling
+      // even though the name might start with ".L".
+      OutStreamer->emitSymbolAttribute(CurrentFnLocalForEH, MCSA_Local);
+      OutStreamer->emitSymbolAttribute(CurrentFnLocalForEH,
+                                       MCSA_ELF_TypeFunction);
+      OutStreamer->emitAssignment(
+          CurrentFnLocalForEH,
+          MCSymbolRefExpr::create(CurrentFnSymForSize, OutContext));
+      OutStreamer->emitELFSize(CurrentFnLocalForEH, SizeExp);
```
Comment (jrtc27) [inline llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1453]: The local and assignment probably shouldn't be under hasDotTypeDotSizeDirective even though that's always the case for us?

File: llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll [hunk 3]
```diff
@@ -0,0 +1,130 @@
+; RUN: llc @PURECAP_HARDFLOAT_ARGS@ < %s -o - | FileCheck %s
+; RUN: llc @PURECAP_HARDFLOAT_ARGS@ < %s -o - -filetype=obj | llvm-readobj -r -t - | FileCheck %s --check-prefix=RELOCS
```
Comment (jrtc27) [inline llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll:2]: Is hard float what we use in general even if it doesn't make a difference?

File: llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+@IF-RISCV@; CHECK-NEXT:     .byte 3                   # Call site Encoding = udata4
+@IFNOT-RISCV@; CHECK-NEXT:  .byte 1                   # Call site Encoding = uleb128
+; CHECK-NEXT:  .uleb128 .Lcst_end0-.Lcst_begin0
+; CHECK-NEXT: .Lcst_begin0:
+; CHECK-NEXT:  [[CS_DIRECTIVE:(\.uleb128)|(\.word)]] .Ltmp0-.Lfunc_begin0           # >> Call Site 1 <<
+; CHECK-NEXT:  [[CS_DIRECTIVE]] .Ltmp1-.Ltmp0                  #   Call between .Ltmp0 and .Ltmp1
+; Note: RISC-V uses DW_EH_PE_udata4, so the 0xc marker uses 4 bytes instead of 1
+; CHECK-NEXT:  [[SMALL_CS_DIRECTIVE:(\.byte)|(\.word)]] 12     # (landing pad is a capability)
+; Note: the following line should not be using _Z8do_catchv, but a local alias
+; CHECK-NEXT:  .chericap  .L_Z8do_catchv$eh_alias + .Ltmp2-.Lfunc_begin0   #     jumps to .Ltmp2
```
Comment (jrtc27) [inline llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll:80]: Bit weird to use .Lfunc_begin0 here now we have the alias but it's not _wrong_. I guess it's fine because the earlier fields of the call site use those symbols and we don't want to change things more than we have to.

File: lld/ELF/Arch/Cheri.cpp (hunk 1 above)
Comment (arichardson) [reply lld/ELF/Arch/Cheri.cpp:1110]: I was thinking about a stale libc++.a/libcxxrt.a/libfoo.a in the sysroot.

Comment (jrtc27) [reply lld/ELF/Arch/Cheri.cpp:1110]: Yeah, but updating LLVM isn't going to magically rebuild that

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp (hunk 2 above)
Comment (arichardson) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1453]: Yes, I only did that so I can re-use SizeExp, but I can just move that outside the if?

File: llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll (hunk 3 above)
Comment (arichardson) [reply llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll:2]: I've been using that as the default lately, but can also change it. Or I could add a @DEFAULT_PURECAP_ARGS@ substitution?

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp (hunk 2 above)
Comment (jrtc27) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1453]: The size and type would stay here, but the local and assignment would move out?

File: llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll (hunk 3 above)
Comment (jrtc27) [reply llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll:2]: It's fine if that's what we're using, just wanted to check.

File: lld/ELF/Arch/Cheri.cpp (hunk 1 above)
Comment (arichardson) [reply lld/ELF/Arch/Cheri.cpp:1110]:
```suggestion
                " in exception handling table. Please rebuild your sysroot!\n"
```
Is that better?

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp (hunk 2 above)
Comment (arichardson) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1453]: That would work but then we have .type after the assignment. Not sure it's a problem, but it seems like the wrong order to me.

Comment (jrtc27) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1453]: So do it before the if not after?

Comment (jrtc27) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1453]: If that bothers you you can expose SizeExp then

File: llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+;         return foo();
+;     } catch(int &i) {
+;         return 1;
+;     } catch(...) {
+;         return 2;
+;     }
+; }
+
+@_ZTIi = external dso_local addrspace(200) constant i8 addrspace(200)*
+define dso_local i64 @_Z8do_catchv() local_unnamed_addr addrspace(200) uwtable personality i8 addrspace(200)* bitcast (i32 (...) addrspace(200)* @__gxx_personality_v0 to i8 addrspace(200)*) {
```
[the remark this answers is not in the document]
Comment (arichardson) [reply llvm/test/CodeGen/CHERI-Generic/Inputs/landingpad-non-preemptible.ll:19]: I've changed it to i32 to be the same across all targets.

**Comment by arichardson** [comment]
Will squash the fixup and merge commits if you're happy with this now.

File: lld/ELF/Arch/Cheri.cpp [hunk 6]
```diff
@@ -1101,44 +1101,15 @@ void addCapabilityRelocation(Symbol *sym, RelType type, InputSectionBase *sec,
...
-      assert(!sym->isPreemptible);
-    }
+    // We previously had an ugly workaround here to create a hidden alias for
+    // relocations in the exception table, but this has since been fixed in
+    // the compiler. Add an explicit error here in case someone tries to
+    // link against object files/static libraries from an old toolchain.
+    errorOrWarn("got relocation against preemptible symbol " + toString(*sym) +
+                " in exception handling table. Please recompile this file!\n"
+                ">>> referenced by " +
+                sec->getObjMsg(offset));
```
Comment (jrtc27) [inline lld/ELF/Arch/Cheri.cpp:1112]: Same line?

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp [hunk 7]
```diff
@@ -1430,14 +1431,30 @@ void AsmPrinter::emitFunctionBody() {
...
   }
+  if (CurrentFnLocalForEH) {
+    // For CHERI exception landing pad tables we need a local alias so
+    // that we can emit non-preemptible relocations with the correct addend.
+    // See https://github.com/CTSRD-CHERI/llvm-project/issues/512.
+    // Note: We add .local so that the symbol is not deleted after assembling
+    // even though the name might start with ".L".
+    OutStreamer->emitSymbolAttribute(CurrentFnLocalForEH, MCSA_Local);
+    OutStreamer->emitSymbolAttribute(CurrentFnLocalForEH,
+                                     MCSA_ELF_TypeFunction);
```
Comment (jrtc27) [inline llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1451]: Needs guarding with hasDotTypeDotSizeDirective

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp [hunk 8]
```diff
@@ -1182,9 +1182,10 @@ void AsmPrinter::emitStackSizeSection(const MachineFunction &MF) {
...
 }
 
-static bool needFuncLabelsForEHOrDebugInfo(const MachineFunction &MF) {
-  MachineModuleInfo &MMI = MF.getMMI();
-  if (!MF.getLandingPads().empty() || MF.hasEHFunclets() || MMI.hasDebugInfo())
+static bool needFuncLabelsForEHOrDebugInfo(const MachineFunction &MF,
+                                           bool IncludeDebugInfo = true) {
+  if (!MF.getLandingPads().empty() || MF.hasEHFunclets() ||
+      (IncludeDebugInfo && MF.getMMI().hasDebugInfo()))
     return true;
```
Comment (jrtc27) [inline llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1189]: Maybe nicer to split it?

```suggestion
static bool needFuncLabelsForEHOrDebugInfo(const MachineFunction &MF) {
  return MF.getMMI().hasDebugInfo() || needFuncLabelsForEH(MF);
}

static bool needFuncLabelsForEH(const MachineFunction &MF) {
  if (!MF.getLandingPads().empty() || MF.hasEHFunclets())
    return true;
```

Or you can do:

```suggestion
static bool needFuncLabelsForEH(const MachineFunction &MF) {
  return needFuncLabelsForEHOrDebugInfo(MF, false);
}

static bool needFuncLabelsForEHOrDebugInfo(const MachineFunction &MF,
                                           bool IncludeDebugInfo = true) {
  if (!MF.getLandingPads().empty() || MF.hasEHFunclets() ||
      (IncludeDebugInfo && MF.getMMI().hasDebugInfo()))
    return true;
```

I guess, though I don't like that as much (but still better than having an `AOrB` where you pass `/*IncludeB=*/false` in uses that aren't wrappers IMO)

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp (hunk 7 above)
Comment (arichardson) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1451]: I looked at emitSymbolAttribute() and that function already does this check. Also it might allow emitting an appropriate directive for non-ELF too.

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp (hunk 8 above)
Comment (arichardson) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1189]: There are only two uses, so splitting it sounds reasonable.

File: lld/ELF/Arch/Cheri.cpp (hunk 6 above)
Comment (arichardson) [reply lld/ELF/Arch/Cheri.cpp:1112]: Formatting of string arguments is one of the things I really don't like about clang-format. Even so, I'd rather use the tool-enforced style (mostly because I have a pre-commit script that checks that all my changes are clang-formatted).

Comment (jrtc27) [reply lld/ELF/Arch/Cheri.cpp:1112]: If it's clang-format then fine

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp (hunk 7 above)
Comment (jrtc27) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1451]: Hm, guess there's redundancy then in the places I looked

Comment (arichardson) [reply llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1453]: Looking more closely: WASM does the following:
`Symbol->setType(wasm::WASM_SYMBOL_TYPE_FUNCTION)`, mach-o+winCOFF simply return false and
`MCXCOFFStreamer` asserts. But I think we can probably ignore XCOFF for CHERI EH...

**Review by jrtc27 — APPROVED** [review]

**Comment by jrtc27** [comment]
I assume CI failures are unrelated issues from the upstream merge?

**Comment by arichardson** [comment]
> I assume CI failures are unrelated issues from the upstream merge?

Yes that's the CLANG_ROUND_TRIP_CC1_ARGS issue, which I only just noticed locally after doing a clean build.
